server {
    listen 80;

    client_max_body_size 20M;

    location / {
        root /usr/share/nginx/html;
        index public/index.html;
        try_files $uri $uri/ =404;
    }

    # アップロードファイルの配信
    location /uploads/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location /api {
        proxy_pass http://backend:8000/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
