"""add recommend table

Revision ID: 96c9859d726d
Revises: 
Create Date: 2026-05-20 14:22:40.280612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c9859d726d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('api_id', sa.TEXT(), nullable=False),
    sa.Column('api_etag', sa.TEXT(), nullable=True),
    sa.Column('self_link', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('publisher', sa.TEXT(), nullable=True),
    sa.Column('published_date', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('total_pages', sa.INTEGER(), nullable=True),
    sa.Column('small_cover_url', sa.TEXT(), nullable=True),
    sa.Column('cover_url', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    # ### end Alembic commands ###
